---
label: Project
hide_body: false
fields:
- type: text
  name: template
  label: template
  hidden: true
- type: text
  name: title
  label: Title
- type: image_gallery
  name: gallery
  label: Gallery
pages:
- content/projects/the-whilst-walking-tour.md
